### ISSUE TITLE
Ideal technical changes to the space before RC2021

### ISSUE THREAD

**Issue by lazerwalker** [Roguelike-Celebration/azure-mud#434]
After triaging our issue tracker, here are a handful of issues that I think would make disproportionate impact to the 2021 conf, irrespective of whether we get videochat or the scripting language in place. 

The first one is really the most important; the rest are all more "nice to have".

- [x] #83 
This actually solves 3 separate problems:
- People complained that they needed a Twitter or Google account to login. This would allow email or mobile phone login
- Signing in with Safari (desktop or iOS) is awkward, and requires disabling 3rd-party cookies (#116)
- We had an infuriating and difficult-to-debug issue where chat would stop working every so often and people would need to refresh the page. I'm 90% sure this is a cookie expiration issue caused by Azure auth, and that Firebase will fix it: #353

- [ ] #394. I just added notes to that ticket with what I think is the minimum viable version of this.

- [x] #432. I've already made this change, I just need to cherry-pick in the single commit from a WIP branch to `main` and make sure it doesn't break things. Playtesting of this TBD since it is a user-facing change.

- [ ] #212, #433. Basically, I think it would be helpful to have _some_ way of differentiating active users and people who are just idling. Giving people the tools to self-mark as idle or eager for conversation is far easier than trying to tell programmatically, but also potentially less useful. This is fuzzy and ill-defined; happy to have discussions here.

- [ ] #155. Splitting out "here are chat messages you sent/received before moving to the room you're in now" should be a quick change (just client-side React within a single component) but should make things less confusing. Relatively low priority compared to other things on this list, but also relatively low effort.

- [ ] #48. Do a UI design pass on our mobile support. Feedback last year is mostly that it worked _fine_ but wasn't particularly good. This is a potentially deep rabbithole; tread carefully.

I care a lot about #222, but I also recognize it's _significantly_ more complex than most of these issues from both a design and implementation standpoint, and is also tied up in whether or not we have videochat support (since if we do have built-in videochat, it would be irresponsible to build in blocking without supporting it in videochat, which _extremely_ complicates things)
