### ISSUE TITLE
Bug Bash for Sunday 9/11 - TODO Triage These

### ISSUE THREAD

**Issue by lazerwalker** [Roguelike-Celebration/azure-mud#642]
**Bugs**
- [x] Cannot make non-mods into mods (the menu doesn't exist when you click their name)
- [x] Hidden rooms show up in the list of rooms until you click through to them (note for Em: add the hidden flag to MinimalRoom)
- [x] Alexei had a JS error. See screenshot. (fix: check roomData AND users. Add count to presence, maybe?)
- [x] Badges are unlocking multiple times, sometimes without user behavior (confirm it's not when other users unlock them)
- [x] Can have multiple copies of a badge in "all badges"
- [x] Can't unequip a badge? (this is apparently a new feature, d'oh, but one that should exist)
- [x] Badges for some users are adding line breaks (see: MuffiTuffiWuffi and MoyTravis, screenshot)
- [ ] Badge boxes are visually off in Windows browsers
- [ ] Kawa had an error when trying to equip a badge "Uncaught SyntaxError: Unexpected end of JSON input", BadgesModalView.tsx:44, JSON.parse
- [ ] Private message "send" button character wraps (on Chrome/Mac, see Sam screenshot)
- [ ] Theater presence is showing 14 people when < 14 people are there (wontfix, old ghost users)
- [ ] Make "undefined" links red so it's easier for us to find

**Content chores**
- [x] Link the Eventbrite on the main/2022 page
- [x] Clean up 2021 schedule
- [ ] Delete unused rooms from the DB/CMS
- [ ] Swag table
- [ ] Office of Steam
- [x] Happening now
- [x] Clean out all note walls (except for graffiti in bar)
- [ ] Re-add ways to change text color
- [ ] Re-add ways to change font (link action = `pentagramMinimalist`)
- [x] "Riddles in The Dungeon's Maze have line breaks showing as text rather than breaking lines"
- [x] Add Office of Transmutations to visual map?
- [ ] Make sure all room links are bidirectional (i.e. you can always get back to the room you came from via links, except for intentional cases)
- [ ] Enable videochat in video dome
- [ ] Link main event in the space
- [x] Add a contributor/thanks room (follow-up: Swag Table has a link to GH contributors, do we need more?)

**Undefined links:**
(workflow: once all of these are fixed and production looks good, someone should click "export to JSON" in the CMS and open a PR with the fixed data)
- [x] Adventurer's Guild -> Office of Transmutations
- [x] "Try one" interaction prompt in the experimental bio lab
- [x] Office of Transmutation has a few
- [x] Unconference room links (fixed on prod, needs JSON PR)

**Design Feedback**
- [ ] "It's confusing to have badges which are slightly dimmer to indicate that they're not available as opposed to, like, having a "unlocked/locked" field."
- [ ] To test on Sunday: will user autocomplete break with 100+ people in theater?
- [ ] when you move it clears you room history, which means you might miss messages (fix: show either "current room messages" OR "most recent 30 messages, or alternatively always show current room + previous room)

**Possible features:**
- [ ] Autocomplete for whisper
- [ ] /help would be nice with some table styling
- [ ] Add separate "make past speaker" toggle that awards a regular badge

**Comment by kawa-kitsuragi** [comment]
wontfix:
 "Riddles in The Dungeon's Maze have line breaks showing as text rather than breaking lines"
- this room should have been deleted anyway
 Add Office of Transmutations to visual map?
- this room is deleted in favor of Experimental Biology
